version: "3.9"

services:

  instance:
    container_name: instance
    image: senaite/senaite:2.x
    restart: "unless-stopped"
    command: fg
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 4GB
    environment:   
      ADDONS: "senaite.databox plone.reload"
      SOURCES: "senaite.databox=git https://github.com/senaite/senaite.databox.git branch=master"
    
    volumes:
      # we need to be selective here, because build files with symlinks, e.g. parts/omelette, cause problems.
      - senaite_vol:/data/.


volumes:
  senaite_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'C:\DockerLimsEnvFiles\senaite\data'
